name: nitsche_corners

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        pip install scikit-fem==1.0.0 jupyter matplotlib

    - name: Run notebook
      run: |
        jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=600 --execute nitsche_stiff_3.ipynb
        sh extract.sh

    - uses: actions/upload-artifact@v2
      with:
        name: ex3
        path: ex3*
